[package]
name = "thokr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = { version = "0.17", default-features = false, features = ['termion'] }
serde = { version = "1.0", features = ["derive"] }
clap = { version = "3.1.1", features = ["derive"] }
serde_json = "*"
rand = "0.8.5"
itertools = "0.10.3"
unicode-width = "*"
webbrowser = "0.6.0"
termion="1.5"
simple-logging = "2.0.2"
log = "0.4.16"
strum_macros = "0.24.0"
include_dir = "0.7.2"
